"""Stable identifier rules for Evo records."""

from __future__ import annotations

from typing import Literal
from uuid import uuid4

IdentifierKind = Literal[
    "event",
    "run",
    "session",
    "plan",
    "node",
    "memory",
    "memory_change",
    "context_pack",
    "candidate",
    "artifact",
    "evidence",
    "evaluation",
    "promotion",
    "shadow_trial",
    "eval_case",
    "eval_variant",
    "eval_trial",
    "corpus",
    "self_model",
]


class EvoIdentifierError(ValueError):
    """Raised when an Evo identifier cannot be safely persisted."""


def new_evo_id(kind: IdentifierKind) -> str:
    """Create a human-searchable, opaque Evo identifier."""

    return f"{kind}_{uuid4().hex[:16]}"


def require_evo_id(value: object, *, field: str, kind: IdentifierKind | None = None) -> str:
    """Validate an identifier without imposing a storage-specific format.

    Imported records may use IDs generated by an older implementation, so the
    contract validates safety and stability properties rather than requiring a
    particular prefix. ``kind`` is accepted for callers that want to document
    the semantic role at the call site.
    """

    del kind
    if not isinstance(value, str) or not value or value.strip() != value:
        raise EvoIdentifierError(f"{field} must be a non-blank identifier")
    if len(value) > 256:
        raise EvoIdentifierError(f"{field} must be at most 256 characters")
    if any(character.isspace() or ord(character) < 32 or ord(character) == 127 for character in value):
        raise EvoIdentifierError(f"{field} must not contain whitespace or control characters")
    return value
