"""会影响缓存、压缩和投影可信度的策略版本。"""

SYSTEM_PROMPT_VERSION = "v18"
COMPACTION_STRATEGY_VERSION = "v2"
ARCHIVE_SCHEMA_VERSION = "v2"
TASK_BOUNDARY_TOOL_VERSION = "v1"
CHECKPOINT_STRATEGY_VERSION = "v1"
CONTEXT_EVENT_SCHEMA_VERSION = "v2"
